version: '3.8'

services:
  mysql:
    image: ubuntu/mysql:8.4-24.04_edge
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: helm-proxy
      MYSQL_USER: helm_user
      MYSQL_PASSWORD: HelmProxy@2026!
      TZ: Asia/Shanghai
    networks:
      - helm-proxy
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot_password"]
      interval: 10s
      timeout: 5s
      retries: 5

  helm-proxy:
    image: veater/helm-proxy:latest
    container_name: helm-proxy
    ports:
      - "8081:8081"
    environment:
      DB_URL: jdbc:mysql://mysql:3306/helm-proxy?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
      DB_USERNAME: helm_user
      DB_PASSWORD: HelmProxy@2026!
      TZ: Asia/Shanghai
      HTTP_PROXY: http://192.168.80.2:10909/
      HTTPS_PROXY: http://192.168.80.2:10909/
      NO_PROXY: localhost,127.0.0.1,mysql
    networks:
      - helm-proxy
    depends_on:
      mysql:
        condition: service_healthy

networks:
  helm-proxy:
    driver: bridge

volumes:
  mysql_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './mysql/data'
