version: '3.8'

services:
  mysql:
    image: ubuntu/mysql:8.4-24.04_edge
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: helm-proxy
      MYSQL_USER: helm_user
      MYSQL_PASSWORD: HelmProxy@2026!
      TZ: Asia/Shanghai
    networks:
      - helm-proxy
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot_password"]
      interval: 10s
      timeout: 5s
      retries: 5

  helm-proxy:
    image: veater/helm-proxy:latest
    container_name: helm-proxy
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/helm-proxy?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
      SPRING_DATASOURCE_USERNAME: helm_user
      SPRING_DATASOURCE_PASSWORD: HelmProxy@2026!
      TZ: Asia/Shanghai
    networks:
      - helm-proxy
    depends_on:
      mysql:
        condition: service_healthy

networks:
  helm-proxy:
    driver: bridge
